---
title: "statements"
author: "Lydia Lucchesi"
date: "20/10/2020"
output: html_document
---

# snap 1
The first three rows of data were extracted from a feature titled "Mid-engine spectacular" in the June 1974 issue of Motor Trend magazine. According to the report, the cars were selected for the feature because of their fuel efficiency: "The prime focal point is on the tiny ones that get the best mileage from a gallon of gold. We scooped up a Fiat 128, a Toyota Corolla 1200 and a Honda Civic."

# snap 2
Each month, the Motor Trend magazine publishes "road tests," systematically reporting performance metrics for several cars. Like the three rows above, these four rows of data were extracted from the 1974 June issue, specifically, from the road test section titled "The Fearsome Foursome," an exploration of whether or not these American pony cars are worth one's consideration when buying a vehicle.




text <- paste("Iris data set gives the measurements in cm",
             "of the variables sepal length and width",
             "and petal length and width, respectively,",
             "for 50 flowers from each of 3 species of iris.",
             "The species are Iris setosa, versicolor, and virginica.", sep = " ")
text.p <- ggparagraph(text, family = "serif", size = 10)
text.p
         
         
         