---
title: "Captions for the smallset timeline"
author: 
date: 2022-01-11
output: html_document
---

Timeline title: Smallset Timeline for Replicating Preprocessing of MDP CM1 Dataset

Timeline subtitle: 

Timeline footnote: Applying translation of preprocessing steps proposed in Gray et al. (2011)

### Starting smallset

Caption: The Smallset contains 10 of the 505 rows in CM1. 18 of the 41 attributes are shown here. All attributes affected by the preprocessing steps are included in the timeline. **Step 1:** All constant attributes are removed from the dataset. These attributes do not offer any useful information when building the classifier. There are three constant attributes in the CM1 dataset: *Global_data_complexity*, *Global_data_density*, and *Pathological_complexity*.

### `mdpData <- mdpData`

Caption: **Step 2:** Remove repeated attributes. There are none in CM1.

### `mdpData$DECISION_DENSITY[is.na(mdpData$DECISION_DENSITY)] <- 0`

Caption: **Step 3:** The *Decision_density* attribute is the only attribute that contains missing values in CM1. This attribute is equal to the *Condition_count* divided by the *Decision_count*. Missing values only occur in *Decision_density* when both of these other attributes equal zero. In other MDP datasets, where both equal zero, so does *Decision_density*. Thus, the missing values are replaced with zero. (161 rows affected)

### `mdpData <- mdpData`

Caption: **Step 4:** All instances which fail one or more of the data integrity checks are removed from the dataset. The integrity checks identify instances that cannot realistically happen. The following integrity checks are used: *Num_operands* + *Num_operators* = *Halstead_length*; *Cyclomatic_complexity* <= *Num_operators* + 1; *Cyclomatic_complexity* >= 1; *Call_pairs* <= *Num_operators*. (0 rows affected)

### `# STEP 5: Remove repeated and inconsistent cases`

Caption: **Step 5:** Remove repeated and inconsistent case. Duplicates are dropped (49 rows affected). Inconsistent cases refer to cases in which all values but the class label are equal, and these are dropped as well (2 rows affected).

### Ending smallset

Caption: The CM1 dataset is preprocessed and ready to be used in the analysis. The full version of CM1 and the R preprocessing code are available on GitHub (insert link here).
