---
title: "Captions for the smallset timeline"
author: 
date: 2022-01-11
output: html_document
---

Timeline title: Smallset Timeline

Timeline subtitle:  Preprocessing the NASA MDP CM1 Dataset for Classification Modelling

Timeline footnote: Applying translation of preprocessing steps proposed in Gray et al. (2011)

### Starting smallset

Caption: This Smallset contains 6 of the 505 rows in the CM1 defect dataset. 13 of the 41 columns are shown here. All columns affected by preprocessing are included. **Step 1:** Remove columns that have the same value for every row. These do not provide any information for modelling.

### `mdpData$DECISION_DENSITY[is.na(mdpData$DECISION_DENSITY)] <- 0`

Caption: **Step 2:** Replace missing *Decision_density* values with zero. Based on other MDP datasets without missing *Decision_density* values, one can deduce that they likely occurred due to a division by zero error and can accurately be replaced with zeros.

### `# STEP 5: Remove repeated and inconsistent cases`

Caption: **Step 3:** Remove rows that are duplicates of other rows to assure models are tested on unseen data only. Also remove rows that are inconsistent, meaning all column values are the same except for one: *Defective* (one row is classified as defective and the other is not).

### Ending smallset

Caption: The CM1 dataset is now ready for use in the modelling and testing stage. The full dataset and R preprocessing code are available on GitHub (insert link here).
