---
title: "Captions for the smallset timeline"
author: 
date: 2022-01-10
output: html_document
---

Timeline title: Smallset Timeline

Timeline subtitle: Alternative preprocessing approach, 22.5K income threshold selection

Timeline footnote: Census data retrieved with the folktables tool

### Starting smallset

Caption: The Smallset in this timeline consists of 6 rows randomly sampled from the 2015 California census income data (n = 374,943). We first subset the dataset to people older than 16 years of age (*Agep*).

### `ca_data <- subset(ca_data, AGEP > 16)`

Caption: Although it is common, with these data, to remove people who report an income less than 100 dollars or do not have a recorded value for average weekly hours worked (*Wkhp*), we want to retain these observations in the dataset. As a result of keeping all income levels, some incomes in the dataset are negative because some people report losses. We replace missing values in the *Wkhp* column with zero. Additionally, after checking that all survey person weights (*Pwgtp*) are greater than or equal to one, we drop the *Pwgtp* column so it is not included in modelling.

### Ending smallset

Caption: For the prediction task, we create a binary income variable (*I22_5k*): those who earn more than 22,500 dollars and those who earn less than or equal to that amount. We select the income threshold based on the median income (*Pincp*) after subsetting the dataset to people older than 16 years of age. The dataset is now preprocessed and ready to be used in benchmarking.
