---
title: "Captions for the smallset timeline"
author: Lydia Lucchesi
date: 2021-09-30
output: html_document
---

Timeline title: Smallset Timeline

Timeline subtitle: Data Preprocessing: Calculate Call Times and Infer Gender

Timeline footnote: "gender" software/paper: https://github.com/ropensci/gender; Blevins & Mullen (2015)

### Starting smallset

Caption: The Smallset is composed of six rows from the phone call dataset (n = 1,000). Four rows are manually selected. Two are randomly sampled. Each instance has a caller's name, age, area code, and phone call time.

### `dat$Time <- (dat$Min * 60) + dat$Sec`

Caption: The *Time* column represents total call time in seconds. It is equal to minutes (*Min*) multiplied by 60 plus seconds (*Sec*). Prior to the calculation, zeros are inserted where *Min* is missing as it means the call was less than one minute.

### `  }`

Caption: Gender is inferred with the "gender" software, which uses U.S. Social Security Administration (SSA) data. Inputs to the algorithm are first names and birthdate ranges (set to 20 years). Birthdates (*Year*) are found via *Age*. For each year, SSA only includes names that occur more than five times. Sometimes, predictions cannot be made based on the data. Rows without predictions are removed.

### Ending smallset

Caption: The phone call data are now prepared for the analysis of call time by gender and age. Preprocessing was conducted in the R software language.
